server: 
  port: 9999
spring: 
  datasource: 
    url: "jdbc:mysql://cabhow-mysql.clqccbf6ffm3.ap-south-1.rds.amazonaws.com/cabhow"
    username: "admin"
    password: "Sarangi#1"
  jpa: 
    hibernate: 
      ddl-auto: validate
      naming: 
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties: 
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        dialect: org.hibernate.dialect.MySQLDialect
      max_allowed_packet: 2000